import time


print("I fell for your magic")
time.sleep(4)
print("I tasted your skin")
time.sleep(5)
print("And though this is tragic")
time.sleep(3)
print("At least I found the end")
time.sleep(4)
print("I witness your madness")
time.sleep(4)
print("You shed light on my sins")
time.sleep(5)
print("And if we share in this sadness")
time.sleep(4)
print("Then where have you been?\n")
time.sleep(3)


print("I know you're not in love")
time.sleep(2)
print("Like you used to be")
time.sleep(3)
print("Guess I'm not the one")
time.sleep(2)
print("Like you used to think")
time.sleep(2)
print("So you just")
time.sleep(1)
print("run\n")
time.sleep(7)


print("I know that I'm stuck")
time.sleep(2)
print("In this misery")
time.sleep(2)
print("Guess I'm not enough")
time.sleep(3)
print("Like you used to think")
time.sleep(2)
print("So I'll just")
time.sleep(1)
print("run")
time.sleep(8)


print("You bathe in your victory")
time.sleep(4)
print("You blew out on my fuse")
time.sleep(5)
print("And if I took on the planet")
time.sleep(3)
print("Will I pay my dues?")
time.sleep(4)
print("Your love was a mystery")
time.sleep(4)
print("Yeah my love is a fool")
time.sleep(5)
print("And I traveled the country")
time.sleep(4)
print("Just to get to you")
time.sleep(3)


